config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :containers

  devise_for :users

  root to: "home#index"

end

app/models/container.rb
class Container < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :containers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  before_action :set_container, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /containers
  # GET /containers.json
  def index
    @containers = Container.all
  end

  # GET /containers/1
  # GET /containers/1.json
  def show
  end

  # GET /containers/new
  def new
    @container = Container.new
  end

  # GET /containers/1/edit
  def edit
  end

  # POST /containers
  # POST /containers.json
  def create
    @container = Container.new(container_params)

    respond_to do |format|
      if @container.save
        format.html { redirect_to @container, notice: 'Container was successfully created.' }
        format.json { render :show, status: :created, location: @container }
      else
        format.html { render :new }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /containers/1
  # PATCH/PUT /containers/1.json
  def update
    respond_to do |format|
      if @container.update(container_params)
        format.html { redirect_to @container, notice: 'Container was successfully updated.' }
        format.json { render :show, status: :ok, location: @container }
      else
        format.html { render :edit }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /containers/1
  # DELETE /containers/1.json
  def destroy
    @container.destroy
    respond_to do |format|
      format.html { redirect_to containers_url, notice: 'Container was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_container
      @container = Container.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def container_params
      params.require(:container).permit(:description, :volume_ml, :volume_oz, :refillable, :last_refill_date, :expiration_date, :empty, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  	if user_signed_in?
  		redirect_to containers_path
  	else
  		redirect_to new_user_session_path
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/containers/_form.html.erb
<%= form_for(@container) do |f| %>
  <% if @container.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@container.errors.count, "error") %> prohibited this container from being saved:</h2>

      <ul>
      <% @container.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :volume_ml %><br>
    <%= f.text_field :volume_ml %>
  </div>
  <div class="field">
    <%= f.label :volume_oz %><br>
    <%= f.text_field :volume_oz %>
  </div>
  <div class="field">
    <%= f.label :refillable %><br>
    <%= f.check_box :refillable %>
  </div>
  <div class="field">
    <%= f.label :last_refill_date %><br>
    <%= f.date_select :last_refill_date %>
  </div>
  <div class="field">
    <%= f.label :expiration_date %><br>
    <%= f.date_select :expiration_date %>
  </div>
  <div class="field">
    <%= f.label :empty %><br>
    <%= f.check_box :empty %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/containers/edit.html.erb
<h1>Editing Container</h1>

<%= render 'form' %>

<%= link_to 'Show', @container %> |
<%= link_to 'Back', containers_path %>

app/views/containers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Containers</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Volume ml</th>
      <th>Volume oz</th>
      <th>Refillable</th>
      <th>Last refill date</th>
      <th>Expiration date</th>
      <th>Empty</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @containers.each do |container| %>
      <tr>
        <td><%= container.description %></td>
        <td><%= container.volume_ml %></td>
        <td><%= container.volume_oz %></td>
        <td><%= container.refillable %></td>
        <td><%= container.last_refill_date %></td>
        <td><%= container.expiration_date %></td>
        <td><%= container.empty %></td>
        <td><%= container.user %></td>
        <td><%= link_to 'Show', container %></td>
        <td><%= link_to 'Edit', edit_container_path(container) %></td>
        <td><%= link_to 'Destroy', container, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Container', new_container_path %>

app/views/containers/new.html.erb
<h1>New Container</h1>

<%= render 'form' %>

<%= link_to 'Back', containers_path %>

app/views/containers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @container.description %>
</p>

<p>
  <strong>Volume ml:</strong>
  <%= @container.volume_ml %>
</p>

<p>
  <strong>Volume oz:</strong>
  <%= @container.volume_oz %>
</p>

<p>
  <strong>Refillable:</strong>
  <%= @container.refillable %>
</p>

<p>
  <strong>Last refill date:</strong>
  <%= @container.last_refill_date %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%= @container.expiration_date %>
</p>

<p>
  <strong>Empty:</strong>
  <%= @container.empty %>
</p>

<p>
  <strong>User:</strong>
  <%= @container.user %>
</p>

<%= link_to 'Edit', edit_container_path(@container) %> |
<%= link_to 'Back', containers_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>H2oManage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <p>Hello, <%= current_user.email %> - <%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %></p>
  <% else %>
  <p>Please <%= link_to "Sign In", new_user_session_path, :method => 'get' %> or <%= link_to "Sign Up", new_user_registration_path, :method => 'get' %></p>
  <% end %>
<%= yield %>

</body>
</html>